import re
import shlex
import textwrap

import tilelang
import tvm


GENERATOR_PATH = "ggml/src/ggml-tilelang/kernels/gen_kernels.py"
GENERATED_KERNEL_NAMES = {
    "w8a8_quant_x": "tilelang_generated_w8a8_quant_x_kernel",
    "w8a8_dot": "tilelang_generated_w8a8_dot_kernel",
    "w8a8_quant_x_rows": "tilelang_generated_w8a8_quant_x_rows_kernel",
    "w8a8_quant_from_partial_max_rows": "tilelang_generated_w8a8_quant_from_partial_max_rows_kernel",
    "w8a8_silu_mul_quant_rows": "tilelang_generated_w8a8_silu_mul_quant_rows_kernel",
    "w8a8_gemm_dot": "tilelang_generated_w8a8_gemm_dot_kernel",
    "w8a8_gemm_dot_narrow_n": "tilelang_generated_w8a8_gemm_dot_narrow_n_kernel",
    "w8a8_gate_up_silu_scaled_gemm_dot_partial_max": "tilelang_generated_w8a8_gate_up_silu_scaled_gemm_dot_partial_max_kernel",
}


def provenance_header(target: str, command: list[str]) -> str:
    command_line = " ".join(shlex.quote(arg) for arg in command)
    tilelang_version = getattr(tilelang, "__version__", "unknown")

    return textwrap.dedent(
        f"""\
        // Generated by {GENERATOR_PATH}
        // TileLang version: {tilelang_version}
        // Target: {target}
        // Command: {command_line}
        // Do not edit manually.
        """
    )

def cuda_sync_helper_source() -> str:
    return textwrap.dedent(
        """\
        static bool tilelang_cuda_sync_enabled() {
            const char * env = std::getenv("GGML_TILELANG_SYNC");
            return env != nullptr && env[0] != '\\0' && env[0] != '0';
        }

        static void tilelang_cuda_debug_sync(cudaStream_t stream) {
            if (!tilelang_cuda_sync_enabled()) {
                return;
            }

            if (stream != nullptr) {
                cudaStreamSynchronize(stream);
            } else {
                cudaDeviceSynchronize();
            }
        }

        """
    )

def normalize_cuda_source(source: str, kernel_name: str, header: str, keep_tl_templates: bool = False) -> str:
    source, count = re.subn(r"\bmain_kernel\b", kernel_name, source)
    if count == 0:
        raise RuntimeError("TileLang CUDA source did not contain main_kernel")

    tl_template_warning_push = textwrap.dedent(
        """\
        #if defined(__GNUC__) || defined(__clang__)
        #pragma GCC diagnostic push
        #pragma GCC diagnostic ignored "-Wunused-parameter"
        #pragma GCC diagnostic ignored "-Wmissing-declarations"
        #pragma GCC diagnostic ignored "-Wmissing-noreturn"
        #endif
        #if defined(__NVCC__)
        #pragma nv_diag_suppress 20012
        #endif
        """
    ).splitlines()
    tl_template_warning_pop = textwrap.dedent(
        """\
        #if defined(__GNUC__) || defined(__clang__)
        #pragma GCC diagnostic pop
        #endif
        #if defined(__NVCC__)
        #pragma nv_diag_default 20012
        #endif
        """
    ).splitlines()

    lines = []
    skip_bf16_block = False
    in_tl_template_includes = False
    for line in source.splitlines():
        if in_tl_template_includes:
            if keep_tl_templates and line.startswith("#include <tl_templates/"):
                lines.append(line)
                continue
            else:
                lines.extend(tl_template_warning_pop)
                in_tl_template_includes = False
        if line == "#ifdef ENABLE_BF16":
            skip_bf16_block = True
            continue
        if skip_bf16_block:
            if line == "#endif":
                skip_bf16_block = False
            continue
        if not keep_tl_templates and line.startswith("#include <tl_templates/"):
            continue
        if keep_tl_templates and line.startswith("#include <tl_templates/"):
            lines.extend(tl_template_warning_push)
            in_tl_template_includes = True
            lines.append(line)
            continue
        lines.append(line)
    if in_tl_template_includes:
        lines.extend(tl_template_warning_pop)
    source = "\n".join(lines).strip() + "\n"

    needs_warp_reduce_max = "w8a8" in kernel_name
    math_include = "#include <math.h>\n" if needs_warp_reduce_max else ""
    warp_reduce_max_source = textwrap.dedent(
        """\
        __device__ __forceinline__ float warp_reduce_max(float value) {
            for (int offset = 16; offset > 0; offset >>= 1) {
                value = fmaxf(value, __shfl_down_sync(0xffffffff, value, offset));
            }
            return value;
        }
        """
    ) if needs_warp_reduce_max else ""

    aliases = ""
    if not keep_tl_templates:
        alias_lines = []
        if re.search(r"\bhalf_t\b", source):
            alias_lines.append("using half_t = half;")
        if re.search(r"\buchar\b", source):
            alias_lines.append("using uchar = unsigned char;")
        if re.search(r"\bushort\b", source):
            alias_lines.append("using ushort = unsigned short;")
        if alias_lines:
            aliases = "\n".join(alias_lines) + "\n\n"

    prefix = header + textwrap.dedent(
        """\
        #include <cuda_fp16.h>
        #include <cuda_runtime.h>
        #include <stdint.h>
        """
    ) + math_include + "\n" + aliases + textwrap.dedent(
        """\
        #ifndef TILELANG_AOT_WARP_REDUCE_SUM_DEFINED
        #define TILELANG_AOT_WARP_REDUCE_SUM_DEFINED
        namespace tl {
        __device__ __forceinline__ int warp_reduce_sum(int value) {
            for (int offset = 16; offset > 0; offset >>= 1) {
                value += __shfl_down_sync(0xffffffff, value, offset);
            }
            return value;
        }

        __device__ __forceinline__ float warp_reduce_sum(float value) {
            for (int offset = 16; offset > 0; offset >>= 1) {
                value += __shfl_down_sync(0xffffffff, value, offset);
            }
            return value;
        }
        """
    ) + warp_reduce_max_source + textwrap.dedent(
        """\
        }
        #endif

        """
    )
    return prefix + source

def lower_cuda_source(
        program,
        target: str,
        kernel_name: str,
        header: str,
        keep_tl_templates: bool = False) -> str:
    with tvm.target.Target(target):
        artifact = tilelang.lower(
            program,
            target=target,
            enable_host_codegen=False,
            enable_device_compile=False,
        )
    return normalize_cuda_source(
        artifact.kernel_source,
        kernel_name=kernel_name,
        header=header,
        keep_tl_templates=keep_tl_templates)
